# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
